@startuml Potion Management Design

class User{
    +id: Long
    +username: String
    +password: String
    +fullName: String
    +email: String
    +address: String
    +roleId: Role
    +active: boolean
    +createdAt: LocalDateTime
    +updatedAt: LocalDateTime
}

class Role {
    +id: Long
    +type: String
}

class Item{
    +id: Long
    +type: String
    +name: String
    +description: String
    +createdAt: LocalDateTime
    +updatedAt: LocalDateTime
}
User "1" -- "1" Role: Can be

User "1" -- "*" Item : Creates

@enduml