spring:
  application:
    name: potion
    version: 1.0.0  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/potion_managers?options=-c%20timezone=America/Santiago}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    defer-datasource-initialization: true
    database: postgresql
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      data-locations:
      - classpath*:db/data.sql
      mode: always


server:
  port: 9001